---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-backup
  name: zookeeper-backup
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-backup
  template:
    metadata:
      labels:
        app: zookeeper-backup
    spec:
      containers:
      - image: library/zookeeper:3.4.13
        imagePullPolicy: IfNotPresent
        name: zookeeper-backup
        ports:
        - containerPort: 2181
        env:
        - name: ZOO_MY_ID
          value: "1"
